<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WSAMZN-MVKF1909" failures="3" tests="31" name="com.gapi.testCases.CreateRemoteHandsTicket" time="261.374" errors="0" timestamp="2023-05-19T18:18:41 IST" skipped="3">
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.461"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="12.169"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="0.270"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.485"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRHTicketForInvalidUser" time="0.236"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketAndVerifyEndToEndFlow" time="5.439">
    <failure message="expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.gapi.testCases.AddCommentsToTheRemoteHandsTicket.addCommentsToTheExistingTicket(AddCommentsToTheRemoteHandsTicket.java:91)
at com.gapi.utilities.TestUtilities.addCommentToTheRequestAndVerify(TestUtilities.java:473)
at com.gapi.testCases.CreateRemoteHandsTicket.createRemoteHandsTicketAndVerifyEndToEndFlow(CreateRemoteHandsTicket.java:124)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createRemoteHandsTicketAndVerifyEndToEndFlow -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketAndVerifyEndToEndFlow" time="8.487">
    <skipped/>
  </testcase> <!-- createRemoteHandsTicketAndVerifyEndToEndFlow -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="10.589"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.986"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.551"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.484"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketAndVerifyEndToEndFlow" time="5.222">
    <skipped/>
  </testcase> <!-- createRemoteHandsTicketAndVerifyEndToEndFlow -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketAndVerifyEndToEndFlow" time="5.601">
    <failure message="expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.gapi.testCases.AddCommentsToTheRemoteHandsTicket.addCommentsToTheExistingTicket(AddCommentsToTheRemoteHandsTicket.java:91)
at com.gapi.utilities.TestUtilities.addCommentToTheRequestAndVerify(TestUtilities.java:473)
at com.gapi.testCases.CreateRemoteHandsTicket.createRemoteHandsTicketAndVerifyEndToEndFlow(CreateRemoteHandsTicket.java:124)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createRemoteHandsTicketAndVerifyEndToEndFlow -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.236"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.328"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="10.661"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketwithNotificationRecipient" time="6.171"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="0.285"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketAndVerifyEndToEndFlow" time="5.484">
    <failure message="expected [200] but found [500]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [500]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.gapi.testCases.AddCommentsToTheRemoteHandsTicket.addCommentsToTheExistingTicket(AddCommentsToTheRemoteHandsTicket.java:91)
at com.gapi.utilities.TestUtilities.addCommentToTheRequestAndVerify(TestUtilities.java:473)
at com.gapi.testCases.CreateRemoteHandsTicket.createRemoteHandsTicketAndVerifyEndToEndFlow(CreateRemoteHandsTicket.java:124)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createRemoteHandsTicketAndVerifyEndToEndFlow -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.284"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.550"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.732"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="10.465"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.507"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="0.276"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="12.255"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.204"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketAndVerifyEndToEndFlow" time="5.644">
    <skipped/>
  </testcase> <!-- createRemoteHandsTicketAndVerifyEndToEndFlow -->
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="11.872"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="createRemoteHandsTicketwithNotificationRecipient" time="0.264"/>
  <system-out/>
  <testcase classname="com.gapi.testCases.CreateRemoteHandsTicket" name="verifyCreateRemoteHandsTicket" time="12.176"/>
  <system-out/>
</testsuite> <!-- com.gapi.testCases.CreateRemoteHandsTicket -->
